WITH new_rows(type, model, serial_number, asset_id, equipment_id, asset_type, mac_ip, responsible, allocated_user, sector, warranty, equipment_state, notes) AS (
  VALUES
  ('Licença', 'Copilot Add-on', NULL, 'sousamara.sousa@planejamento.gov.br', '', 'SW', '', 'Mara Helena Sousa', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rodriguesmariana.rodrigues@planejamento.gov.br', '', 'SW', '', 'Mariana Cunha Eleutério Rodrigues', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'netomario.valverde@planejamento.gov.br', '', 'SW', '', 'Mario dos Santos Morais Valverde Neto', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'salgadomaristella.salgado@planejamento.gov.br', '', 'SW', '', 'Maristella Alves do Nascimento Salgado', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'annananahira.rabelo@planejamento.gov.br', '', 'SW', '', 'Nanahira de Rabelo e Sant''Anna', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rochapaulo-n.rocha@planejamento.gov.br', '', 'SW', '', 'Paulo Eduardo Nunes de Moura Rocha', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'silvapedro.barbosa@planejamento.gov.br', '', 'SW', '', 'Pedro Barbosa da Silva', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'sganzerlapriscilla.pimentel@planejamento.gov.br', '', 'SW', '', 'Priscilla Rosa Pimentel Sganzerla', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'jeaner.silva@planejamento.gov.br', '', 'SW', '', 'Jeaner Luis de Paula Silva', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'luiz.gondin@planejamento.gov.br', '', 'SW', '', 'Luiz Gondin', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'luzia.melo@planejamento.gov.br', '', 'SW', '', 'Luzia Maria Cavalcante de Mello', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'maira.costa@planejamento.gov.br', '', 'SW', '', 'Maíra Murrieta Costa', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'mara.sousa@planejamento.gov.br', '', 'SW', '', 'Mara Helena Sousa', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'marcelo.prudente@planejamento.gov.br', '', 'SW', '', 'Marcelo Augusto Prudente Lima', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'marcelo.s.pereira@planejamento.gov.br', '', 'SW', '', 'Marcelo De Souza Pereira', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'matheus.soares@planejamento.gov.br', '', 'SW', '', 'Matheus Varanda Soares', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'priscilla.pimentel@planejamento.gov.br', '', 'SW', '', 'Priscilla Rosa Pimentel Sganzerla', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'suia.rocha@planejamento.gov.br', '', 'SW', '', 'Suia Kafure Da Rocha', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'vitor.goncalves@planejamento.gov.br', '', 'SW', '', 'Vitor Gabriel Gonçalves Da Silva', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'waldeck.araujo@planejamento.gov.br', '', 'SW', '', 'Waldeck Pinto de Araujo Junior', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'welton.barros@planejamento.gov.br', '', 'SW', '', 'Welton Barros', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'davi-r.silva@planejamento.gov.br', '', 'SW', '', 'Davi Santana Cesar Rodrigues da Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'eduardo.stuani@planejamento.gov.br', '', 'SW', '', 'Eduardo do Nascimento Stuani', '', 'COTIC', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'gustavo.gumaraes@planejamento.gov.br', '', 'SW', '', 'Gustavo José de Guimarães e Souza', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'leandro.lira@planejamento.gov.br', '', 'SW', '', 'Leandro de Lima Lira', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'mario.valverde@planejamento.gov.br', '', 'SW', '', 'Mário dos Santos Morais Valverde Neto', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'ricardo.teixeira@planejamento.gov.br', '', 'SW', '', 'Ricardo de Assis Teixeira', '', 'CGEST', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'vinicius.jovito@planejamento.gov.br', '', 'SW', '', 'Vinícius Soares Jovito', '', 'COTIC', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'cristiane.carvalho@planejamento.gov.br', '', 'SW', '', 'Cristiane Gonzaga Chaves de Carvalho', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'denise.gontijo@planejamento.gov.br', '', 'SW', '', 'Denise Herminio Gontijo', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'fabiano.chaves@planejamento.gov.br', '', 'SW', '', 'Fabiano Chaves da Silva', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'oscar.zveiter@planejamento.gov.br', '', 'SW', '', 'Oscar Zveiter Neto', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'cesar.mascarenhas@planejamento.gov.br', '', 'SW', '', 'César Augusto Assis Mascarenhas de Oliveira', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'daniel.s.coelho@planejamento.gov.br', '', 'SW', '', 'Daniel Souza Coelho', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'edimilson.oliveira@planejamento.gov.br', '', 'SW', '', 'Edimilson Torres de Oliveira Neto', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'hermann.mirindiba@planejamento.gov.br', '', 'SW', '', 'Hermann Moraes Mirindiba', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'raquel.sampaio@planejamento.gov.br', '', 'SW', '', 'Raquel Braga Barreto Sampaio', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'mauro.t.santos@planejamento.gov.br', '', 'SW', '', 'Mauro Tapajós Santos', '', 'SE', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'monade.costa@planejamento.gov.br', '', 'SW', '', 'Monade Rassa Souza Costa', '', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'nelson.fonseca@planejamento.gov.br', '', 'SW', '', 'Nelson Sattler da Fonseca', '', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'alvaro.carneiro@planejamento.gov.br', '', 'SW', '', 'Álvaro José de Andrade Carneiro', '', 'COTIC', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'daniel.reiss@planejamento.gov.br', '', 'SW', '', 'Daniel Gersten Reiss', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'thomaz.fronzaglia@planejamento.gov.br', '', 'SW', '', 'Thomaz Fronzaglia', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'gustavo.bruzzeguez@planejamento.gov.br', '', 'SW', '', 'Gustavo Andrade Bruzzeguez', '', 'CGTCO', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'luciano.pacheco@planejamento.gov.br', '', 'SW', '', 'Luciano da Silva Pacheco', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'joao.figueredo@planejamento.gov.br', '', 'SW', '', 'João Gabriel Dias Figueredo', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'leonardo.c.mello@planejamento.gov.br', '', 'SW', '', 'Leonardo Mello', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rodolfo.aguiar@planejamento.gov.br', '', 'SW', '', 'Rodolfo Vaz Oliveira Aguiar', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'luiz.a.neto@planejamento.gov.br', '', 'SW', '', 'Luiz Alves Antonio Neto', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'jorge.arbex@planejamento.gov.br', '', 'SW', '', 'Jorge Toufic Arbex', '', 'COTIC', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'luiz.h.moreira@planejamento.gov.br', '', 'SW', '', 'Luiz Henrique Moreira', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'marcelo.shinkoda@planejamento.gov.br', '', 'SW', '', 'Marcelo Shinkoda', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'pedro.aguiar@planejamento.gov.br', '', 'SW', '', 'Pedro De Souza Aguiar', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'ricardo.almeida@planejamento.gov.br', '', 'SW', '', 'Ricardo Almeida Carvalho', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'rodrigo.c.silva@planejamento.gov.br', '', 'SW', '', 'Rodrigo Cardoso Da Silva', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Planner Plan', NULL, 'david.meister@planejamento.gov.br', '', 'SW', '', 'David Meister', '', '', '', 'Ativa', 'Planner Plan atribuída'),
  ('Licença', 'CDAO Executive Team Member', NULL, 'everton.ramos@planejamento.gov.br', '', 'SW', '', 'Everton Batista Ramos', '', 'SOF', '', 'Ativa', 'Licença Gartner - CDAO Executive Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Leader', NULL, 'ramon.brandao@planejamento.gov.br', '', 'Licença', '', 'Ramon Gomes Brandão', 'Ramon Gomes Brandão', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Leader atribuída'),
  ('Licença', 'Gartner for Technical Professionals Member', NULL, 'wertiz.silva-junior@planejamento.gov.br', '', 'Licença', '', 'Wertiz Dantas da Silva Junior', 'Wertiz Dantas da Silva Junior', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'andreia.r.santos@planejamento.gov.br', '', 'SW', '', 'Andreia Rodrigues Dos Santos', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Gartner for Technical Professionals Member', NULL, 'ricardo.peixoto@planejamento.gov.br', '', 'Licença', '', 'Ricardo Tadeu de Albuquerque Peixoto', 'Ricardo Tadeu de Albuquerque Peixoto', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'claudinei.souza@planejamento.gov.br', '', 'SW', '', 'Claudiney Cardoso De Souza', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'daniel.bandarrinha@planejamento.gov.br', '', 'SW', '', 'Daniel De Figueiredo Bandarrinha', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'edson.hoji@planejamento.gov.br', '', 'SW', '', 'Edson Yukio Hoji', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'erick.ribeiro@planejamento.gov.br', '', 'SW', '', 'Erick Fagundes Ribeiro', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'estela.medeiros@planejamento.gov.br', '', 'SW', '', 'Estela Alves De Medeiros', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'glaucio.charao@planejamento.gov.br', '', 'SW', '', 'Gláucio Rafael Da Rocha Charão', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'hugo.val@planejamento.gov.br', '', 'SW', '', 'Hugo Torres do Val', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'lucas.s.vieira@planejamento.gov.br', '', 'SW', '', 'Lucas Da Silva Vieira', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'adriana.a.silva@planejamento.gov.br', '', 'SW', '', 'Adriana Amorim da Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'alisson.boas@planejamento.gov.br', '', 'SW', '', 'Alisson Vilas Boas', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'andre.henriques@planejamento.gov.br', '', 'SW', '', 'Andre Santiago Henriques', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'basemate.santos@planejamento.gov.br', '', 'SW', '', 'Basemate Oliveira dos Santos', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'camila.curi@planejamento.gov.br', '', 'SW', '', 'Camila Barbosa Curi', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'cecilia.nascimento@planejamento.gov.br', '', 'SW', '', 'Cecília Umetsu do Nascimento', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'lea.nobrega@planejamento.gov.br', '', 'Licença', '', 'Lea Mendonça Nobrega', 'Lea Mendonça Nobrega', 'DIORC', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'edmar.oliveira@planejamento.gov.br', '', 'SW', '', 'Edmar Silva de Oliveira', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'elayne.batista@planejamento.gov.br', '', 'SW', '', 'Elayne Maria da Silva Batista', '', 'DIORC', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'iane.azevedo@planejamento.gov.br', '', 'SW', '', 'Ianê de Andrade Azevedo', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'isadora.colombo@planejamento.gov.br', '', 'SW', '', 'Isadora do Carmo Colombo', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'jean.ferreira@planejamento.gov.br', '', 'SW', '', 'Jean Carlos Moura Ferreira', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'jonatas.santos@planejamento.gov.br', '', 'SW', '', 'Jônatas D''Alma Costa Santos', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'marcelo.r.moreira@planejamento.gov.br', '', 'SW', '', 'Marcelo Ribeiro Moreira', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'nanahira.rabelo@planejamento.gov.br', '', 'SW', '', 'Nanahira de Rabelo e Sant''Anna', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'paulo-n.rocha@planejamento.gov.br', '', 'SW', '', 'Paulo Eduardo Nunes de Moura Rocha', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'paulo.possas@planejamento.gov.br', '', 'SW', '', 'Paulo Henrique Possas', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'raquel.ferrari@planejamento.gov.br', '', 'SW', '', 'Raquel Ferrari da Veiga', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'socorro.lima@planejamento.gov.br', '', 'SW', '', 'Socorro Lima', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'taissa.vieira@planejamento.gov.br', '', 'SW', '', 'Taissa Thieme de Barros Vieira', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'thomaz.silva@planejamento.gov.br', '', 'SW', '', 'Thomaz Milani Rodrigues Muroni Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'andrea.bertolini@planejamento.gov.br', '', 'SW', '', 'Andrea Curiacos Bertolini', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'arthur.feitoza@planejamento.gov.br', '', 'SW', '', 'Arthur Feitoza de Oliveira', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'beatriz.yamada@planejamento.gov.br', '', 'SW', '', 'Beatriz Leão Yamada', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'clarice.marinho@planejamento.gov.br', '', 'SW', '', 'Clarice Fernandes Marinho', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'douglas.saymom@planejamento.gov.br', '', 'SW', '', 'Douglas Saymom de Freitas Ferreira', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'eduardo.m.silva@planejamento.gov.br', '', 'SW', '', 'Eduardo Moura da Silva', '', 'CGEST', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'emanuele.queiros@planejamento.gov.br', '', 'SW', '', 'Emanuele dos Santos Queiros', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'emanuele.marrocos@planejamento.gov.br', '', 'SW', '', 'Emanuele Raquel de Oliveira Marrocos', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'felipe.piletti@planejamento.gov.br', '', 'SW', '', 'Felipe José Piletti', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'thiago.reis@planejamento.gov.br', '', 'SW', '', 'Thiago Tavares Reis', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'marcos.fonseca@planejamento.gov.br', '', 'Licença', '', 'Marcos César Chaves da Fonseca', 'Marcos César Chaves da Fonseca', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'ronan.leal@planejamento.gov.br', '', 'SW', '', 'Ronan Ramos Leal', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'anael.jacob@planejamento.gov.br', '', 'SW', '', 'Anael Aymore Jacob', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'claudio.navarro@planejamento.gov.br', '', 'SW', '', 'Cláudio  Alexandre de Area Leão Navarro', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'joao.figuereido@planejamento.gov.br', '', 'SW', '', 'João Gabriel Dias Figuereido', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rafael.neto@planejamento.gov.br', '', 'SW', '', 'Rafael Martins Neto', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rodolfo.marques@planejamento.gov.br', '', 'SW', '', 'Rodolfo Marques Santos', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'italo.soares@planejamento.gov.br', '', 'SW', '', 'Ítalo Nogueira Soares', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'rafael.ibsen@planejamento.gov.br', '', 'SW', '', 'Rafael Ibsen Souza Silva', '', 'CONTB', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'eduardo.m.araujo@planejamento.gov.br', '', 'Licença', '', 'Eduardo Moreira Araújo', 'Eduardo Moreira Araújo', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'cassio.faria@planejamento.gov.br', '', 'SW', '', 'Cassio Lucas de Faria', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'clayton.silva@planejamento.gov.br', '', 'SW', '', 'Clayton Rodrigues Da Silva', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'daniel.r.costa@planejamento.gov.br', '', 'SW', '', 'Daniel Ramos Costa', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'danielle.mota@planejamento.gov.br', '', 'SW', '', 'Danielle Cavagnolle Mota', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'diego.fernandes@planejamento.gov.br', '', 'SW', '', 'Diego dos Santos Fernandes', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'gabriel-s.lima@planejamento.gov.br', '', 'SW', '', 'Gabriel Silva Lima', '', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Copilot Studio', NULL, 'matheus.pereira@planejamento.gov.br', '', 'SW', '', 'Matheus Maurício Rodrigues Pereira', '', 'CGEST', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'joao.g.barreto@planejamento.gov.br', '', 'Licença', '', 'João Carlos Gonçalves Barreto', 'João Carlos Gonçalves Barreto', '', '', 'Ativa', 'Power BI Pro atribu├¡da'),
  ('Licença', 'Power BI Pro', NULL, 'karlei.rodrigues@planejamento.gov.br', '', 'SW', '', 'Karlei Scardua Rodrigues', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'filipe.duarte@planejamento.gov.br', '', 'SW', '', 'Filipe Tomaz Figueiredo Duarte', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'karina.martins@planejamento.gov.br', '', 'Licença', '', 'Karina Rocha Martins', 'Karina Rocha Martins', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'karine.costa@planejamento.gov.br', '', 'Licença', '', 'Karine Patrício Costa', 'Karine Patrício Costa', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Gartner CDAO Executive Team Member', NULL, 'silvafelipe.csilva@planejamento.gov.br', '', 'Licença', '', 'Felipe Cesar Araujo Da Silva', 'Felipe Cesar Araujo Da Silva', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'adrieny.guterres@planejamento.gov.br', '', 'SW', '', 'Adrieny Azeredo Guterres', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'ana.dantas@planejamento.gov.br', '', 'SW', '', 'Ana Carolina de Souza Dantas', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'bandarrinhadaniel.bandarrinha@planejamento.gov.br', '', 'SW', '', 'Daniel de Figueiredo Bandarrinha', '', 'SOF', '', 'Ativa', 'Licença Gartner - Technical Professionals Team Member atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'daniel.rezende@planejamento.gov.br', '', 'SW', '', 'Daniel Oliveira De Rezende', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'felipe.csilva@planejamento.gov.br', '', 'SW', '', 'Felipe Cesar Araujo da Silva', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'ferreiraadalberto.ferreira@planejamento.gov.br', '', 'SW', '', 'Adalberto Rodrigues Ferreira', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'gabriela.gomes@planejamento.gov.br', '', 'SW', '', 'Gabriela Pires Gomes de Sousa Costa', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'ivan.stemler@planejamento.gov.br', '', 'SW', '', 'Ivan Sasha Viana Stemler', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'jose.mascarenhas@planejamento.gov.br', '', 'SW', '', 'Jose Paulo de Araujo Mascarenhas', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'guterresadrieny.guterres@planejamento.gov.br', '', 'SW', '', 'Adrieny Azeredo Guterres', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'martinsallex.martins@planejamento.gov.br', '', 'SW', '', 'Allex Carneiro Martins', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'custodioana.custodio@planejamento.gov.br', '', 'SW', '', 'Ana Laura Sousa e Custodio', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'lessaana.lessa@planejamento.gov.br', '', 'SW', '', 'Ana Vitória Santos Lessa', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'filhoantonio.s.filho@planejamento.gov.br', '', 'SW', '', 'Antônio Sabino da Costa Filho', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'santosclaudia.avila@planejamento.gov.br', '', 'SW', '', 'Claudia Campos de Ávila Santos', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'lilian.faula@planejamento.gov.br', '', 'SW', '', 'Lilian Chaves Maluf Faula', '', 'SE/SAGE/CGEST', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'nayla.gomes@planejamento.gov.br', '', 'SW', '', 'Nayla Cunha Gomes', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'viviane.barros@planejamento.gov.br', '', 'Licença', '', 'Viviane Gomes De Barros Nóbrega', 'Viviane Gomes De Barros Nóbrega', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'samantha.cavadinha@planejamento.gov.br', '', 'SW', '', 'Samantha Lemos Turte Cavadinha', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'canedoclaudia.canedo@planejamento.gov.br', '', 'SW', '', 'Claudia Regina Tavares Canedo', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'monteiroclaudio.monteiro@planejamento.gov.br', '', 'SW', '', 'Cláudio Martins Neiva Monteiro', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'arbexdeborah.arbex@planejamento.gov.br', '', 'SW', '', 'Deborah Ferreira Arbex', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'felipe.caixeta@planejamento.gov.br', '', 'SW', '', 'Felipe Caixeta Carvalho', '', '', '', 'Ativa', 'Copilot Add-on atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'henrique.nagazawa@planejamento.gov.br', '', 'SW', '', 'Henrique Eiti Otaguiri Nagazawa', '', 'SE/SAGE/CGTOP/COTIC', '', 'Ativa', 'Copilot Add-on atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'pamela.lemos@planejamento.gov.br', '', 'SW', '', 'Pamela Vanessa Knoup Siqueira Lemos', '', '', '', 'Ativa', 'Copilot Add-on atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'paulo-r.leite@planejamento.gov.br', '', 'SW', '', 'Paulo Henrique da Rocha Leite', '', 'CONTB', '', 'Ativa', 'Copilot Add-on atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'rafael.gangana@planejamento.gov.br', '', 'SW', '', 'Rafael Saldanha Ferraz Gangana', '', 'COEFI', '', 'Ativa', 'Copilot Add-on atribu├¡da'),
  ('Licença', 'Copilot Studio', NULL, 'guilherme.oliveira@planejamento.gov.br', '', 'SW', '', 'Guilherme Resende Oliveira', '', '', '', 'Ativa', 'Copilot Studio atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'marquesdilso.marques@planejamento.gov.br', '', 'SW', '', 'Dilso Marvell Marques', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'andre.monteiro@planejamento.gov.br', '', 'Licença', '', 'André do Nascimento Monteiro', 'André do Nascimento Monteiro', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'carlene.souza@planejamento.gov.br', '', 'Licença', '', 'Carlene Guimarães de Souza', 'Carlene Guimarães de Souza', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Copilot Studio', NULL, 'raphael.amaro@planejamento.gov.br', '', 'SW', '', 'Raphael Silveira Amaro', '', '', '', 'Ativa', 'Copilot Studio atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'geraldo.francisco@planejamento.gov.br', '', 'Licença', '', 'Geraldo Francisco da Silva Júnior', 'Geraldo Francisco da Silva Júnior', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'jessica.orion@planejamento.gov.br', '', 'Licença', '', 'Jessica Ellen Azevedo Orion Lopes', 'Jessica Ellen Azevedo Orion Lopes', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'amarildo.lima@planejamento.gov.br', '', 'Licença', '', 'José Amarildo Nunes de Lima', 'José Amarildo Nunes de Lima', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Copilot Studio', NULL, 'vinicius.araujo@planejamento.gov.br', '', 'Licença', '', 'Vinícius Araújo dos Santos', 'Vinícius Araújo dos Santos', '', '', 'Ativa', 'Copilot Studio atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'bruno.sousa@planejamento.gov.br', '', 'SW', '', 'Bruno Sousa de Oliveira', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'carlos.renato@planejamento.gov.br', '', 'SW', '', 'Carlos Renato de Melo Castro', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'daniel.grimaldi@planejamento.gov.br', '', 'SW', '', 'Daniel da Silva Grimaldi', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'daniela.farias@planejamento.gov.br', '', 'SW', '', 'Daniela Mesquita de Farias', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'denise.dias@planejamento.gov.br', '', 'SW', '', 'Denise Galana Gomes Dias', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'dilso.marques@planejamento.gov.br', '', 'SW', '', 'Dilso Marvell Marques', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'emily.damasceno@planejamento.gov.br', '', 'SW', '', 'Emily Silva Damasceno', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'flavia.pereira@planejamento.gov.br', '', 'SW', '', 'Flavia Pedrosa Pereira', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'iara.tillmann@planejamento.gov.br', '', 'SW', '', 'Iara Marina de Oliveira Tillmann', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'keliane.cavalcante@planejamento.gov.br', '', 'SW', '', 'Keliane de Oliveira Cavalcante', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'larissa.vieira@planejamento.gov.br', '', 'SW', '', 'Larissa Martins Vieira', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'laurinei.martins@planejamento.gov.br', '', 'Licença', '', 'Laurinei Pimentel Martins', 'Laurinei Pimentel Martins', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'mirian.fiuza@planejamento.gov.br', '', 'Licença', '', 'Mirian de Fátima Fiuza de Oliveira', 'Mirian de Fátima Fiuza de Oliveira', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'tatiane.oliveira@planejamento.gov.br', '', 'Licença', '', 'Tatiane Braz De Oliveira', 'Tatiane Braz De Oliveira', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'aguiarelisangela.aguiar@planejamento.gov.br', '', 'SW', '', 'Elisângela Maria de Aguiar', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'vinicius.andrade@planejamento.gov.br', '', 'Licença', '', 'Vinícius Pereira Andrade', 'Vinícius Pereira Andrade', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'marilia.lima@planejamento.gov.br', '', 'Licença', '', 'Marília Oliveira Barbosa Lima', 'Marília Oliveira Barbosa Lima', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'moises.s.carvalho@planejamento.gov.br', '', 'Licença', '', 'Moisés dos Santos Carvalho', 'Moisés dos Santos Carvalho', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'roberta.vieira@planejamento.gov.br', '', 'SW', '', 'Roberta da Silva Vieira', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'roberto.celestino@planejamento.gov.br', '', 'SW', '', 'Roberto Marconne Celestino De Souza', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'rubiane.araujo@planejamento.gov.br', '', 'SW', '', 'Rubiane Rios Ferreira Araujo', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'silvana.silva@planejamento.gov.br', '', 'SW', '', 'Silvana Ribeiro da Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'ubiratan.lucena@planejamento.gov.br', '', 'SW', '', 'Ubiratan Nunes de Lucena', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'willian.bueno@planejamento.gov.br', '', 'SW', '', 'Willian Bueno e Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'zaqueu.silva@planejamento.gov.br', '', 'SW', '', 'Zaqueu Batista da Silva', '', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'emanele.queiros@planejamento.gov.br', '', 'SW', '', 'Emanuele dos Santos Queiros', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribu├¡da'),
  ('Licença', 'Copilot Studio', NULL, 'guilherme.resende@planejamento.gov.br', '', 'SW', '', 'Guilherme Resende Oliveira', '', '', '', 'Ativa', 'Copilot Studio atribu├¡da'),
  ('Licença', 'Acrobat Pro DC', NULL, 'marcus.brandao@planejamento.gov.br', '', 'Licença', '', 'Marcus Vinicius Pereira Brandão', 'Marcus Vinicius Pereira Brandão', '', '', 'Ativa', 'Acrobat Pro DC atribu├¡da'),
  ('Licença', 'Copilot Add-on', NULL, 'santosjonatas.santos@planejamento.gov.br', '', 'SW', '', 'Jônatas D''Alma Costa Santos', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'leitejulio.leite@planejamento.gov.br', '', 'SW', '', 'Júlio Vinícius Alves Leite', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'CDAO Executive Team Leader', NULL, 'bruzzeguezgustavo.bruzzeguez@planejamento.gov.br', '', 'SW', '', 'Gustavo Bruzzeguez', '', '', '', 'Ativa', 'CDAO Executive Team Leader atribuída'),
  ('Licença', 'CDAO Executive Team Member', NULL, 'costadaniel.r.costa@planejamento.gov.br', '', 'SW', '', 'Everton Ramos', '', '', '', 'Ativa', 'CDAO Executive Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Leader', NULL, 'carneiroalvaro.carneiro@planejamento.gov.br', '', 'SW', '', 'Álvaro José de Andrade Carneiro', '', '', '', 'Ativa', 'Gartner for Technical Professionals Team Leader atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'fonsecamarcos.fonseca@planejamento.gov.br', '', 'SW', '', 'Marcos Alsina', '', '', '', 'Ativa', 'Gartner for Technical Professionals Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'liraleandro.lira@planejamento.gov.br', '', 'SW', '', 'Leandro Lira', '', '', '', 'Ativa', 'Gartner for Technical Professionals Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'grimaldidaniel.grimaldi@planejamento.gov.br', '', 'SW', '', 'Wertiz Dantas da Silva Junior', '', '', '', 'Ativa', 'Gartner for Technical Professionals Team Member atribuída'),
  ('Licença', 'Gartner for Technical Professionals Team Member', NULL, 'dantasana.dantas@planejamento.gov.br', '', 'SW', '', 'Monade Rassa Souza Costa', '', '', '', 'Ativa', 'Gartner for Technical Professionals Team Member atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'melloleonardo.c.mello@planejamento.gov.br', '', 'SW', '', 'Leonardo Mello', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Copilot Add-on', NULL, 'santosbasemate.santos@planejamento.gov.br', '', 'SW', '', 'Rodolfo Vaz Oliveira Aguiar', '', '', '', 'Ativa', 'Copilot Add-on atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'cristiane.carvalho@planejamento.gov.br', '', 'SW', '', 'Cristiane Gonzaga Chaves de Carvalho', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'gustavo.guimaraes@planejamento.gov.br', '', 'SW', '', 'Gustavo José de Guimarães e Souza', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'leonardo.c.mello@planejamento.gov.br', '', 'SW', '', 'Leonardo Mello', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'lorena.pompeu@planejamento.gov.br', '', 'SW', '', 'Lorena Ferrer Cavalcanti Randal Pompeu', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'waldeck.araujo@planejamento.gov.br', '', 'SW', '', 'Waldeck Pinto de Araujo Junior', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Acrobat Pro DC', NULL, 'alvaro.carneiro@planejamento.gov.br', '', 'SW', '', 'Álvaro José de Andrade Carneiro', '', '', '', 'Ativa', 'Acrobat Pro DC atribuída'),
  ('Licença', 'Adobe Creative Cloud - All Apps', NULL, 'rodolfo.aguiar@planejamento.gov.br', '', 'SW', '', 'Rodolfo Vaz Oliveira Aguiar', '', '', '', 'Ativa', 'Adobe Creative Cloud - All Apps atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'adalberto.ferreira@planejamento.gov.br', '', 'SW', '', 'Adalberto Rodrigues Ferreira', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'adrieny.guterres@planejamento.gov.br', '', 'SW', '', 'Adrieny Azeredo Guterres', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'allex.martins@planejamento.gov.br', '', 'SW', '', 'Allex Carneiro Martins', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'ana.custodio@planejamento.gov.br', '', 'SW', '', 'Ana Laura Sousa e Custodio', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'ana.lessa@planejamento.gov.br', '', 'SW', '', 'Ana Vitória Santos Lessa', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'anael.jacob@planejamento.gov.br', '', 'SW', '', 'Anael Aymore Jacob', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'antonio.s.filho@planejamento.gov.br', '', 'SW', '', 'Antônio Sabino da Costa Filho', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'claudia.avila@planejamento.gov.br', '', 'SW', '', 'Claudia Campos de Ávila Santos', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'claudia.canedo@planejamento.gov.br', '', 'SW', '', 'Claudia Regina Tavares Canedo', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'claudio.navarro@planejamento.gov.br', '', 'SW', '', 'Cláudio Alexandre de Area Leão Navarro', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'claudio.monteiro@planejamento.gov.br', '', 'SW', '', 'Cláudio Martins Neiva Monteiro', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'cesar.mascarenhas@planejamento.gov.br', '', 'SW', '', 'César Augusto Assis Mascarenhas de Oliveira', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'daniel.reiss@planejamento.gov.br', '', 'SW', '', 'Daniel Gersten Reiss', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'daniel.s.coelho@planejamento.gov.br', '', 'SW', '', 'Daniel Souza Coelho', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'david.meister@planejamento.gov.br', '', 'SW', '', 'David Meister', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'deborah.arbex@planejamento.gov.br', '', 'SW', '', 'Deborah Ferreira Arbex', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'denise.gontijo@planejamento.gov.br', '', 'SW', '', 'Denise Herminio Gontijo', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'dilso.marques@planejamento.gov.br', '', 'SW', '', 'Dilso Marvell Marques', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'edimilson.oliveira@planejamento.gov.br', '', 'SW', '', 'Edimilson Torres de Oliveira Neto', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'eduardo.stuani@planejamento.gov.br', '', 'SW', '', 'Eduardo do Nascimento Stuani', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'elisangela.aguiar@planejamento.gov.br', '', 'SW', '', 'Elisângela Maria de Aguiar', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'fabiano.chaves@planejamento.gov.br', '', 'SW', '', 'Fabiano Chaves da Silva', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'felipe.caixeta@planejamento.gov.br', '', 'SW', '', 'Felipe Caixeta Carvalho', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'flavio.scorza@planejamento.gov.br', '', 'SW', '', 'Flavio Augusto Trevisan Scorza', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'gustavo.bruzzeguez@planejamento.gov.br', '', 'SW', '', 'Gustavo Andrade Bruzzeguez', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'henrique.nagazawa@planejamento.gov.br', '', 'SW', '', 'Henrique Eiti Otaguiri Nagazawa', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'hermann.mirindiba@planejamento.gov.br', '', 'SW', '', 'Hermann Moraes Mirindiba', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'jorge.arbex@planejamento.gov.br', '', 'SW', '', 'Jorge Toufic Arbex', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'joao.figuereido@planejamento.gov.br', '', 'SW', '', 'João Gabriel Dias Figuereido', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'jonatas.santos@planejamento.gov.br', '', 'SW', '', 'Jônatas D''Alma Costa Santos', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'julio.leite@planejamento.gov.br', '', 'SW', '', 'Júlio Vinícius Alves Leite', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'leandro.lira@planejamento.gov.br', '', 'SW', '', 'Leandro de Lima Lira', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'leonardo.c.mello@planejamento.gov.br', '', 'SW', '', 'Leonardo Mello', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'lorena.pompeu@planejamento.gov.br', '', 'SW', '', 'Lorena Ferrer Cavalcanti Randal Pompeu', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'luciano.pacheco@planejamento.gov.br', '', 'SW', '', 'Luciano da Silva Pacheco', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'mara.sousa@planejamento.gov.br', '', 'SW', '', 'Mara Helena Sousa', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'mariana.rodrigues@planejamento.gov.br', '', 'SW', '', 'Mariana Cunha Eleutério Rodrigues', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'mario.valverde@planejamento.gov.br', '', 'SW', '', 'Mario dos Santos Morais Valverde Neto', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'maristella.salgado@planejamento.gov.br', '', 'SW', '', 'Maristella Alves do Nascimento Salgado', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'maira.costa@planejamento.gov.br', '', 'SW', '', 'Maíra Murrieta Costa', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'nanahira.rabelo@planejamento.gov.br', '', 'SW', '', 'Nanahira de Rabelo e SantAnna', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'oscar.zveiter@planejamento.gov.br', '', 'SW', '', 'Oscar Zveiter Neto', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'pamela.lemos@planejamento.gov.br', '', 'SW', '', 'Pamela Vanessa Knoup Siqueira Lemos', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'paulo-n.rocha@planejamento.gov.br', '', 'SW', '', 'Paulo Eduardo Nunes de Moura Rocha', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'paulo-r.leite@planejamento.gov.br', '', 'SW', '', 'Paulo Henrique da Rocha Leite', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'pedro.barbosa@planejamento.gov.br', '', 'SW', '', 'Pedro Barbosa da Silva', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'priscilla.pimentel@planejamento.gov.br', '', 'SW', '', 'Priscilla Rosa Pimentel Sganzerla', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'rafael.ibsen@planejamento.gov.br', '', 'SW', '', 'Rafael Ibsen Souza Silva', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'rafael.neto@planejamento.gov.br', '', 'SW', '', 'Rafael Martins Neto', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'rafael.gangana@planejamento.gov.br', '', 'SW', '', 'Rafael Saldanha Ferraz Gangana', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'raquel.sampaio@planejamento.gov.br', '', 'SW', '', 'Raquel Braga Barreto Sampaio', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'ricardo.teixeira@planejamento.gov.br', '', 'SW', '', 'Ricardo de Assis Teixeira', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'rodolfo.marques@planejamento.gov.br', '', 'SW', '', 'Rodolfo Marques Santos', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'rodolfo.aguiar@planejamento.gov.br', '', 'SW', '', 'Rodolfo Vaz Oliveira Aguiar', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'thomaz.fronzaglia@planejamento.gov.br', '', 'SW', '', 'Thomaz Fronzaglia', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'vinicius.jovito@planejamento.gov.br', '', 'SW', '', 'Vinícius Soares Jovito', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'alvaro.carneiro@planejamento.gov.br', '', 'SW', '', 'Álvaro José de Andrade Carneiro', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Add-on (Microsoft 365 Copilot)', NULL, 'italo.soares@planejamento.gov.br', '', 'SW', '', 'Ítalo Nogueira Soares', '', '', '', 'Ativa', 'Copilot Add-on (Microsoft 365 Copilot) atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'cristiane.carvalho@planejamento.gov.br', '', 'SW', '', 'Cristiane Gonzaga Chaves de Carvalho', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'daniel.reiss@planejamento.gov.br', '', 'SW', '', 'Daniel Gersten Reiss', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'jeaner.silva@planejamento.gov.br', '', 'SW', '', 'Jeaner Luis de Paula Silva', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'leonardo.c.mello@planejamento.gov.br', '', 'SW', '', 'Leonardo Mello', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'matheus.mauricio@planejamento.gov.br', '', 'SW', '', 'Matheus Maurício Rodrigues Pereira', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'mario.valverde@planejamento.gov.br', '', 'SW', '', 'Mário dos Santos Morais Valverde Neto', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'vinicius.a.santos@planejamento.gov.br', '', 'SW', '', 'Vinícius Araújo dos Santos', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'vinicius.jovito@planejamento.gov.br', '', 'SW', '', 'Vinícius Soares Jovito', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Copilot Studio', NULL, 'waldeck.araujo@planejamento.gov.br', '', 'SW', '', 'Waldeck Pinto de Araujo Junior', '', '', '', 'Ativa', 'Copilot Studio atribuída'),
  ('Licença', 'Planner Plan', NULL, 'fabiano.chaves@planejamento.gov.br', '', 'SW', '', 'Fabiano Chaves da Silva', '', '', '', 'Ativa', 'Planner Plan atribuída'),
  ('Licença', 'Planner Plan', NULL, 'raquel.sampaio@planejamento.gov.br', '', 'SW', '', 'Raquel Braga Barreto Sampaio', '', '', '', 'Ativa', 'Planner Plan atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'cesar.mascarenhas@planejamento.gov.br', '', 'SW', '', 'Cesar Augusto Assis Mascarenhas De Oliveira', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'daniel.s.coelho@planejamento.gov.br', '', 'SW', '', 'Daniel Souza Coelho', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'denise.gontijo@planejamento.gov.br', '', 'SW', '', 'Denise Herminio Gontijo', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'edimilson.oliveira@planejamento.gov.br', '', 'SW', '', 'Edimilson Torres de Oliveira Neto', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'everton.ramos@planejamento.gov.br', '', 'SW', '', 'Everton Batista Ramos', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'gustavo.bruzzeguez@planejamento.gov.br', '', 'SW', '', 'Gustavo Andrade Bruzzeguez', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'hermann.mirindiba@planejamento.gov.br', '', 'SW', '', 'Hermann Moraes Mirindiba', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'joao.figuereido@planejamento.gov.br', '', 'SW', '', 'João Gabriel Dias Figuereido', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'luciano.pacheco@planejamento.gov.br', '', 'SW', '', 'Luciano da Silva Pacheco', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'luiz.a.neto@planejamento.gov.br', '', 'SW', '', 'Luiz Alves Antonio Neto', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'luiz.h.moreira@planejamento.gov.br', '', 'SW', '', 'Luiz Henrique Moreira', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'marcelo.shinkoda@planejamento.gov.br', '', 'SW', '', 'Marcelo Shinkoda', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'pedro.aguiar@planejamento.gov.br', '', 'SW', '', 'Pedro De Souza Aguiar', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'ricardo.almeida@planejamento.gov.br', '', 'SW', '', 'Ricardo Almeida Carvalho', '', '', '', 'Ativa', 'Power BI Pro atribuída'),
  ('Licença', 'Power BI Pro', NULL, 'rodrigo.c.silva@planejamento.gov.br', '', 'SW', '', 'Rodrigo Cardoso Da Silva', '', '', '', 'Ativa', 'Power BI Pro atribuída')
)
INSERT INTO inventory_items(type, model, serial_number, asset_id, equipment_id, asset_type, mac_ip, responsible, allocated_user, sector, warranty, equipment_state, notes)
SELECT type, model, serial_number, asset_id, equipment_id, asset_type, mac_ip, responsible, allocated_user, sector, warranty, equipment_state, notes
FROM new_rows nr
WHERE NOT EXISTS (
  SELECT 1 FROM inventory_items i
  WHERE lower(i.type) = lower(nr.type)
    AND lower(i.model) = lower(nr.model)
    AND lower(coalesce(i.asset_id, '')) = lower(coalesce(nr.asset_id, ''))
);
